version: '3.1'
services:
  client:
    build: ./flask_app/client
    container_name: client
    expose:
      - '${CLIENT_PORT}'
    ports:
      - '${CLIENT_PORT}:${GUNICORN_PORT}'
    volumes:
      - './flask_app/client:/app'
      - './certs/rabbitmq:/cert_rabbitmq'
    environment:
      GUNICORN_PORT: '${CLIENT_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CLIENT_IP: '${CLIENT_IP}'
      DELIVERY_IP: '${DELIVERY_IP}'
      MACHINE_IP: '${MACHINE_IP}'
      ORDER_IP: '${ORDER_IP}'
      PAYMENT_IP: '${PAYMENT_IP}'
      RABBITMQ_IP: '${RABBITMQ_IP}'
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_CA_CERT: "${RABBITMQ_CA_CERT}"
      RABBITMQ_CLIENT_KEY: "${RABBITMQ_CLIENT_KEY}"
      RABBITMQ_CLIENT_CERT: "${RABBITMQ_CLIENT_CERT}"
      CONSUL_IP: "${CONSUL_IP}"
      SERVICE_NAME: 'client'
      SERVICE_ID: 'client'
      CONSUL_HOST: '${CONSUL_IP}'
    depends_on:
      - consul
    networks:
      lb7_network:
        ipv4_address: '${CLIENT_IP}'
  delivery:
    build: ./flask_app/delivery
    container_name: delivery
    expose:
      - '${DELIVERY_PORT}'
    ports:
      - '${DELIVERY_PORT}:${GUNICORN_PORT}'
    volumes:
      - './flask_app/delivery:/app'
      - './certs/rabbitmq:/cert_rabbitmq'
    environment:
      GUNICORN_PORT: '${DELIVERY_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CLIENT_IP: '${CLIENT_IP}'
      DELIVERY_IP: '${DELIVERY_IP}'
      MACHINE_IP: '${MACHINE_IP}'
      ORDER_IP: '${ORDER_IP}'
      PAYMENT_IP: '${PAYMENT_IP}'
      RABBITMQ_IP: '${RABBITMQ_IP}'
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_CA_CERT: "${RABBITMQ_CA_CERT}"
      RABBITMQ_CLIENT_KEY: "${RABBITMQ_CLIENT_KEY}"
      RABBITMQ_CLIENT_CERT: "${RABBITMQ_CLIENT_CERT}"
      CONSUL_IP: "${CONSUL_IP}"
      SERVICE_NAME: 'delivery'
      SERVICE_ID: 'delivery'
      CONSUL_HOST: '${CONSUL_IP}'
    depends_on:
      - consul
    networks:
      lb7_network:
        ipv4_address: '${DELIVERY_IP}'
  machine:
    build: ./flask_app/machine
    container_name: machine
    expose:
      - '${MACHINE_PORT}'
    ports:
      - '${MACHINE_PORT}:${GUNICORN_PORT}'
    volumes:
      - './flask_app/machine:/app'
      - './certs/rabbitmq:/cert_rabbitmq'
    environment:
      GUNICORN_PORT: '${MACHINE_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CLIENT_IP: '${CLIENT_IP}'
      DELIVERY_IP: '${DELIVERY_IP}'
      MACHINE_IP: '${MACHINE_IP}'
      ORDER_IP: '${ORDER_IP}'
      PAYMENT_IP: '${PAYMENT_IP}'
      RABBITMQ_IP: '${RABBITMQ_IP}'
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_CA_CERT: "${RABBITMQ_CA_CERT}"
      RABBITMQ_CLIENT_KEY: "${RABBITMQ_CLIENT_KEY}"
      RABBITMQ_CLIENT_CERT: "${RABBITMQ_CLIENT_CERT}"
      CONSUL_IP: "${CONSUL_IP}"
      SERVICE_NAME: 'machine'
      SERVICE_ID: 'machine'
      CONSUL_HOST: '${CONSUL_IP}'
    depends_on:
      - consul
    networks:
      lb7_network:
        ipv4_address: '${MACHINE_IP}'
  order:
    build: ./flask_app/order
    container_name: order
    expose:
      - '${ORDER_PORT}'
    ports:
      - '${ORDER_PORT}:${GUNICORN_PORT}'
    volumes:
      - './flask_app/order:/app'
      - './certs/rabbitmq:/cert_rabbitmq'
    environment:
      GUNICORN_PORT: '${ORDER_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CLIENT_IP: '${CLIENT_IP}'
      DELIVERY_IP: '${DELIVERY_IP}'
      MACHINE_IP: '${MACHINE_IP}'
      ORDER_IP: '${ORDER_IP}'
      PAYMENT_IP: '${PAYMENT_IP}'
      RABBITMQ_IP: '${RABBITMQ_IP}'
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_CA_CERT: "${RABBITMQ_CA_CERT}"
      RABBITMQ_CLIENT_KEY: "${RABBITMQ_CLIENT_KEY}"
      RABBITMQ_CLIENT_CERT: "${RABBITMQ_CLIENT_CERT}"
      CONSUL_IP: "${CONSUL_IP}"
      SERVICE_NAME: 'order'
      SERVICE_ID: 'order'
      CONSUL_HOST: '${CONSUL_IP}'
    depends_on:
      - consul
    networks:
      lb7_network:
        ipv4_address: '${ORDER_IP}'
  payment:
    build: ./flask_app/payment
    container_name: payment
    expose:
      - '${PAYMENT_PORT}'
    ports:
      - '${PAYMENT_PORT}:${GUNICORN_PORT}'
    volumes:
      - './flask_app/payment:/app'
      - './certs/rabbitmq:/cert_rabbitmq'
    environment:
      GUNICORN_PORT: '${PAYMENT_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CLIENT_IP: '${CLIENT_IP}'
      DELIVERY_IP: '${DELIVERY_IP}'
      MACHINE_IP: '${MACHINE_IP}'
      ORDER_IP: '${ORDER_IP}'
      PAYMENT_IP: '${PAYMENT_IP}'
      RABBITMQ_IP: '${RABBITMQ_IP}'
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_CA_CERT: "${RABBITMQ_CA_CERT}"
      RABBITMQ_CLIENT_KEY: "${RABBITMQ_CLIENT_KEY}"
      RABBITMQ_CLIENT_CERT: "${RABBITMQ_CLIENT_CERT}"
      CONSUL_IP: "${CONSUL_IP}"
      SERVICE_NAME: 'payment'
      SERVICE_ID: 'payment'
      CONSUL_HOST: '${CONSUL_IP}'
    depends_on:
      - consul
    networks:
      lb7_network:
        ipv4_address: '${PAYMENT_IP}'
  logs:
    build: ./flask_app/logs
    container_name: logs
    expose:
      - '${LOGS_PORT}'
    ports:
      - '${LOGS_PORT}:${GUNICORN_PORT}'
    volumes:
      - './flask_app/logs:/app'
      - './certs/rabbitmq:/cert_rabbitmq'
    environment:
      GUNICORN_PORT: '${LOGS_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CLIENT_IP: '${CLIENT_IP}'
      DELIVERY_IP: '${DELIVERY_IP}'
      MACHINE_IP: '${MACHINE_IP}'
      ORDER_IP: '${ORDER_IP}'
      LOGS_IP: '${LOGS_IP}'
      PAYMENT_IP: '${PAYMENT_IP}'
      RABBITMQ_IP: '${RABBITMQ_IP}'
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_CA_CERT: "${RABBITMQ_CA_CERT}"
      RABBITMQ_CLIENT_KEY: "${RABBITMQ_CLIENT_KEY}"
      RABBITMQ_CLIENT_CERT: "${RABBITMQ_CLIENT_CERT}"
      CONSUL_IP: "${CONSUL_IP}"
      SERVICE_NAME: 'logs'
      SERVICE_ID: 'logs'
      CONSUL_HOST: '${CONSUL_IP}'
    depends_on:
      - consul
    networks:
      lb7_network:
        ipv4_address: '${LOGS_IP}'
  warehouse:
    build: ./flask_app/warehouse
    container_name: warehouse
    expose:
      - '${WAREHOUSE_PORT}'
    ports:
      - '${WAREHOUSE_PORT}:${GUNICORN_PORT}'
    volumes:
      - './flask_app/warehouse:/app'
      - './certs/rabbitmq:/cert_rabbitmq'
    environment:
      GUNICORN_PORT: '${WAREHOUSE_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
      CLIENT_IP: '${CLIENT_IP}'
      DELIVERY_IP: '${DELIVERY_IP}'
      MACHINE_IP: '${MACHINE_IP}'
      ORDER_IP: '${ORDER_IP}'
      PAYMENT_IP: '${PAYMENT_IP}'
      RABBITMQ_IP: '${RABBITMQ_IP}'
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_CA_CERT: "${RABBITMQ_CA_CERT}"
      RABBITMQ_CLIENT_KEY: "${RABBITMQ_CLIENT_KEY}"
      RABBITMQ_CLIENT_CERT: "${RABBITMQ_CLIENT_CERT}"
      CONSUL_IP: "${CONSUL_IP}"
      SERVICE_NAME: 'warehouse'
      SERVICE_ID: 'warehouse'
      CONSUL_HOST: '${CONSUL_IP}'
    depends_on:
      - consul
    networks:
      lb7_network:
        ipv4_address: '${WAREHOUSE_IP}'
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SSL_CERTFILE: "${RABBITMQ_SERVER_CERT}"
      RABBITMQ_SSL_KEYFILE: "${RABBITMQ_SERVER_KEY}"
      RABBITMQ_SSL_CACERTFILE: "${RABBITMQ_CA_CERT}"
      RABBITMQ_MANAGEMENT_SSL_CERTFILE: "${RABBITMQ_SERVER_CERT}"
      RABBITMQ_MANAGEMENT_SSL_KEYFILE: "${RABBITMQ_SERVER_KEY}"
      RABBITMQ_MANAGEMENT_SSL_CACERTFILE: "${RABBITMQ_CA_CERT}"
    ports:
      - "15671:15671"
      - "5671:5671"
    expose:
      - "15671"
      - "5671"
    networks:
      lb7_network:
        ipv4_address: '${RABBITMQ_IP}'
    volumes:
      - './certs/rabbitmq:/cert_rabbitmq'
  haproxy:
    build: ./haproxy
    ports:
      - '${HAPROXY_PORT}:${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}'
    expose:
      - '${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}'
    volumes:
      - ./certs/haproxy/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem
    networks:
      lb7_network:
        ipv4_address: '${HAPROXY_IP}'
    environment:
      - 'CLIENT_IP=${CLIENT_IP}'
      - 'DELIVERY_IP=${DELIVERY_IP}'
      - 'MACHINE_IP=${MACHINE_IP}'
      - 'ORDER_IP=${ORDER_IP}'
      - 'PAYMENT_IP=${PAYMENT_IP}'
      - 'HAPROXY_PORT=${HAPROXY_PORT}'
      - 'HAPROXY_STATS_PORT=${HAPROXY_STATS_PORT}'
      - 'GUNICORN_PORT=${GUNICORN_PORT}'
      - 'LOGS_IP=${LOGS_IP}'
      - 'CONSUL_IP=${CONSUL_IP}'
      - 'RABBITMQ_IP=${RABBITMQ_IP}'
    restart: unless-stopped
    #db:
    #image: mysql
    #restart: always
    #ports:
    #  - '13306:${MYSQL_PORT}'
    #environment:
    #  MYSQL_DATABASE: '${MYSQL_DATABASE}'
    #  MYSQL_USER: '${MYSQL_USER}'
    #  MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    #  MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
  consul:
      image: 'consul:latest'
      ports:
        - '8300:8300'
        - '8301:8301'
        - '8301:8301/udp'
        - '8500:8500'
        - '8600:8600'
        - '8600:8600/udp'
      networks:
        lb7_network:
          ipv4_address: '${CONSUL_IP}'
networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'

