version: '3.1'
services:
  client:
    build: ./flask_app/client
    expose:
      - '${GUNICORN_PORT}'
    volumes:
      - './flask_app/client:/app'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    networks:
      lb7_network:
        ipv4_address: '${CLIENT_IP}'
  delivery:
    build: ./flask_app/delivery
    expose:
      - '${GUNICORN_PORT}'
    volumes:
      - './flask_app/delivery:/app'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    networks:
      lb7_network:
        ipv4_address: '${DELIVERY_IP}'

  machine:
    build: ./flask_app/machine
    expose:
      - '${GUNICORN_PORT}'
    volumes:
      - './flask_app/machine:/app'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    networks:
      lb7_network:
        ipv4_address: '${MACHINE_IP}'
  order:
    build: ./flask_app/order
    expose:
      - '${GUNICORN_PORT}'
    volumes:
      - './flask_app/order:/app'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    networks:
      lb7_network:
        ipv4_address: '${ORDER_IP}'
  payment:
    build: ./flask_app/payment
    expose:
      - '${GUNICORN_PORT}'
    volumes:
      - './flask_app/payment:/app'
    environment:
      GUNICORN_PORT: '${GUNICORN_PORT}'
      #SQLALCHEMY_DATABASE_URI: 'mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}'
      SQLALCHEMY_DATABASE_URI: '${SQLALCHEMY_SQLITE_DATABASE_URI}'
      SQLALCHEMY_TRACK_MODIFICATIONS: '${SQLALCHEMY_TRACK_MODIFICATIONS}'
    networks:
      lb7_network:
        ipv4_address: '${PAYMENT_IP}'
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      lb7_network:
        ipv4_address: '${RABBITMQ_IP}'
  haproxy:
    build: ./haproxy
    ports:
      - '${HAPROXY_PORT}:${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}:${HAPROXY_STATS_PORT}'
    expose:
      - '${HAPROXY_PORT}'
      - '${HAPROXY_STATS_PORT}'
    volumes:
      - ./haproxy/cert.pem:/usr/local/etc/haproxy/cert.pem
    networks:
      lb7_network:
        ipv4_address: '${HAPROXY_IP}'
    environment:
      - 'CLIENT_IP=${CLIENT_IP}'
      - 'DELIVERY_IP=${DELIVERY_IP}'
      - 'MACHINE_IP=${MACHINE_IP}'
      - 'ORDER_IP=${ORDER_IP}'
      - 'PAYMENT_IP=${PAYMENT_IP}'
      - 'HAPROXY_PORT=${HAPROXY_PORT}'
      - 'HAPROXY_STATS_PORT=${HAPROXY_STATS_PORT}'
      - 'GUNICORN_PORT=${GUNICORN_PORT}'
    restart: unless-stopped
    #db:
    #image: mysql
    #restart: always
    #ports:
    #  - '13306:${MYSQL_PORT}'
    #environment:
    #  MYSQL_DATABASE: '${MYSQL_DATABASE}'
    #  MYSQL_USER: '${MYSQL_USER}'
    #  MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    #  MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

networks:
  lb7_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: '${NETWORK_SUBNET}'

